export type FoodItem = {
  name: string;
  image?: string;
  servingSizeg: number;
  calories: number;
  caloriesFromFat: number;
  totalFatg: number;
  saturatedFatg: number;
  transFatg: number;
  cholesterolmg: number;
  sodiummg: number;
  totalCarbg: number;
  dietaryFiberg: number;
  sugarsg: number;
  proteing: number;
  notes?: string;
};

export const foods: FoodItem[] = [
  {
    name: "Hamburger w/Onion",
    image: "/food/hamburger@2x.png",
    servingSizeg: 208,
    calories: 360,
    caloriesFromFat: 140,
    totalFatg: 16,
    saturatedFatg: 4.5,
    transFatg: 0,
    cholesterolmg: 35,
    sodiummg: 660,
    totalCarbg: 37,
    dietaryFiberg: 2,
    sugarsg: 8,
    proteing: 16,
  },
  {
    name: "Hamburger w/Onion (mustard & ketchup instead of spread)",
    servingSizeg: 201,
    calories: 300,
    caloriesFromFat: 80,
    totalFatg: 9,
    saturatedFatg: 3.5,
    transFatg: 0,
    cholesterolmg: 35,
    sodiummg: 610,
    totalCarbg: 37,
    dietaryFiberg: 2,
    sugarsg: 8,
    proteing: 16,
  },
  {
    name: "Hamburger Protein Style®",
    servingSizeg: 181,
    calories: 200,
    caloriesFromFat: 130,
    totalFatg: 14,
    saturatedFatg: 4.5,
    transFatg: 0,
    cholesterolmg: 35,
    sodiummg: 390,
    totalCarbg: 8,
    dietaryFiberg: 2,
    sugarsg: 5,
    proteing: 12,
    notes: "Bun replaced with lettuce",
  },
  {
    name: "Cheeseburger w/Onion",
    image: "/food/cheeseburger@2x.png",
    servingSizeg: 229,
    calories: 430,
    caloriesFromFat: 190,
    totalFatg: 21,
    saturatedFatg: 8,
    transFatg: 0,
    cholesterolmg: 55,
    sodiummg: 1070,
    totalCarbg: 39,
    dietaryFiberg: 2,
    sugarsg: 8,
    proteing: 20,
  },
  {
    name: "Cheeseburger w/Onion (mustard & ketchup instead of spread)",
    servingSizeg: 222,
    calories: 370,
    caloriesFromFat: 130,
    totalFatg: 15,
    saturatedFatg: 7,
    transFatg: 0,
    cholesterolmg: 55,
    sodiummg: 1020,
    totalCarbg: 39,
    dietaryFiberg: 2,
    sugarsg: 9,
    proteing: 19,
  },
  {
    name: "Cheeseburger Protein Style®",
    servingSizeg: 202,
    calories: 270,
    caloriesFromFat: 170,
    totalFatg: 19,
    saturatedFatg: 8,
    transFatg: 0,
    cholesterolmg: 55,
    sodiummg: 800,
    totalCarbg: 10,
    dietaryFiberg: 2,
    sugarsg: 6,
    proteing: 16,
    notes: "Bun replaced with lettuce",
  },
  {
    name: "Double-Double® w/Onion",
    image: "/food/double-double@2x.png",
    servingSizeg: 286,
    calories: 610,
    caloriesFromFat: 300,
    totalFatg: 34,
    saturatedFatg: 15,
    transFatg: 0,
    cholesterolmg: 110,
    sodiummg: 1660,
    totalCarbg: 41,
    dietaryFiberg: 2,
    sugarsg: 8,
    proteing: 34,
  },
  {
    name: "Double-Double® w/Onion (mustard & ketchup instead of spread)",
    servingSizeg: 279,
    calories: 550,
    caloriesFromFat: 240,
    totalFatg: 27,
    saturatedFatg: 14,
    transFatg: 0,
    cholesterolmg: 105,
    sodiummg: 1600,
    totalCarbg: 41,
    dietaryFiberg: 2,
    sugarsg: 9,
    proteing: 34,
  },
  {
    name: "Double-Double® Protein Style®",
    servingSizeg: 259,
    calories: 450,
    caloriesFromFat: 290,
    totalFatg: 32,
    saturatedFatg: 15,
    transFatg: 0,
    cholesterolmg: 110,
    sodiummg: 1380,
    totalCarbg: 12,
    dietaryFiberg: 2,
    sugarsg: 6,
    proteing: 30,
    notes: "Bun replaced with lettuce",
  },
  {
    name: "French Fries",
    image: "/food/fries@2x.png",
    servingSizeg: 125,
    calories: 360,
    caloriesFromFat: 140,
    totalFatg: 15,
    saturatedFatg: 1.5,
    transFatg: 0,
    cholesterolmg: 0,
    sodiummg: 150,
    totalCarbg: 49,
    dietaryFiberg: 6,
    sugarsg: 0,
    proteing: 6,
  },
  {
    name: "Chocolate Shake 15oz.",
    image: "/food/chocolate-shake@2x.png",
    servingSizeg: 0,
    calories: 610,
    caloriesFromFat: 270,
    totalFatg: 30,
    saturatedFatg: 19,
    transFatg: 1,
    cholesterolmg: 110,
    sodiummg: 370,
    totalCarbg: 74,
    dietaryFiberg: 0,
    sugarsg: 61,
    proteing: 16,
  },
  {
    name: "Vanilla Shake 15oz.",
    image: "/food/vanilla-shake@2x.png",
    servingSizeg: 0,
    calories: 590,
    caloriesFromFat: 280,
    totalFatg: 31,
    saturatedFatg: 20,
    transFatg: 1,
    cholesterolmg: 115,
    sodiummg: 360,
    totalCarbg: 66,
    dietaryFiberg: 0,
    sugarsg: 55,
    proteing: 16,
  },
  {
    name: "Strawberry Shake 15oz.",
    image: "/food/strawberry-shake@2x.png",
    servingSizeg: 0,
    calories: 610,
    caloriesFromFat: 270,
    totalFatg: 30,
    saturatedFatg: 19,
    transFatg: 1,
    cholesterolmg: 110,
    sodiummg: 350,
    totalCarbg: 74,
    dietaryFiberg: 0,
    sugarsg: 63,
    proteing: 15,
  },
  {
    name: "Coffee 15oz.",
    image: "/food/coffee@2x.png",
    servingSizeg: 0,
    calories: 0,
    caloriesFromFat: 0,
    totalFatg: 0,
    saturatedFatg: 0,
    transFatg: 0,
    cholesterolmg: 0,
    sodiummg: 10,
    totalCarbg: 0,
    dietaryFiberg: 0,
    sugarsg: 0,
    proteing: 0,
  },
  {
    name: "Hot Cocoa 8oz.",
    image: "/food/hot-cocoa@2x.png",
    servingSizeg: 0,
    calories: 160,
    caloriesFromFat: 30,
    totalFatg: 3,
    saturatedFatg: 2.5,
    transFatg: 0,
    cholesterolmg: 0,
    sodiummg: 240,
    totalCarbg: 33,
    dietaryFiberg: 2,
    sugarsg: 29,
    proteing: 2,
  },
  {
    name: "Hot Cocoa 8oz. with Marshmallows",
    servingSizeg: 0,
    calories: 180,
    caloriesFromFat: 30,
    totalFatg: 3,
    saturatedFatg: 2.5,
    transFatg: 0,
    cholesterolmg: 0,
    sodiummg: 240,
    totalCarbg: 33,
    dietaryFiberg: 2,
    sugarsg: 34,
    proteing: 2,
  },
  {
    name: "Milk 10oz.",
    image: "/food/milk@2x.png",
    servingSizeg: 0,
    calories: 150,
    caloriesFromFat: 50,
    totalFatg: 6,
    saturatedFatg: 3.5,
    transFatg: 0,
    cholesterolmg: 25,
    sodiummg: 160,
    totalCarbg: 15,
    dietaryFiberg: 0,
    sugarsg: 15,
    proteing: 10,
  },
];

export const addons: FoodItem[] = [
  {
    name: "Pickles",
    servingSizeg: 37,
    calories: 5,
    caloriesFromFat: 0,
    totalFatg: 0,
    saturatedFatg: 0,
    transFatg: 0,
    cholesterolmg: 0,
    sodiummg: 550,
    totalCarbg: 1,
    dietaryFiberg: 0,
    sugarsg: 0,
    proteing: 0,
  },
  {
    name: "Chopped Chilies",
    servingSizeg: 7,
    calories: 0,
    caloriesFromFat: 0,
    totalFatg: 0,
    saturatedFatg: 0,
    transFatg: 0,
    cholesterolmg: 0,
    sodiummg: 90,
    totalCarbg: 0,
    dietaryFiberg: 0,
    sugarsg: 0,
    proteing: 0,
  },
  {
    name: "Grilled Onions",
    servingSizeg: 27,
    calories: 15,
    caloriesFromFat: 0,
    totalFatg: 0,
    saturatedFatg: 0,
    transFatg: 0,
    cholesterolmg: 0,
    sodiummg: 0,
    totalCarbg: 4,
    dietaryFiberg: 1,
    sugarsg: 3,
    proteing: 0,
  },
];
